const CREATE_ADVERTISE = "advertise:CREATE_ADVERTISE";
const GET_ALL_ADVERTISE = "advertise:GET_ALL_ADVERTISE";
const UPDATE_ADVERTISE = "advertise:UPDATE_ADVERTISE";
const DELETE_ADVERTISE = "advertise:DELETE_ADVERTISE";
module.exports ={
    CREATE_ADVERTISE,
    GET_ALL_ADVERTISE,
    UPDATE_ADVERTISE,
    DELETE_ADVERTISE,
}